---
title: "Experiences"
---

\  

## Norfolk Southern Corporation, Data Science Coop (Atlanta, GA)
May 2019 - Aug 2019

- Positive Train Control Analysis (Python: pandas, SciPy, scikit-learn)
-- Designed student t-test and Mann-Whitney U test to detect bad signal reception locomotives and waysides, and an ensemble method composed of DBSCAN and distance constraints to remove irrelevant waysides.

-	Locomotive Lube Oil Fault Detection (Python: pandas, joblib, H2O, Keras)
--	Explored the pattern of data by anomaly detection using sparse auto-encoder and LSTM multivariate auto-encoder. Created time-related features and employed weight-penalized random forest to predict the current “fault” label (~2000:1), 3 days in advance, achieving the recall ~0.30 and precision ~0.60, previously no obvious pattern. 



## Tulane University, Statistics Ph.D. (New Orleans, LA) 
Aug 2014 - Present

R: data.table, RStan

- Comprehensive statistical analysis of DNA methylation Data

- Created a multivariate Poisson mixed model with spatial structure and estimate parameters by Bayeisan inference

- Built hidden markov model to detect differential methylated regions on chromosome