---
title: "Projects"
---

\  

## Default Rate Prediction for Lending Club Data (R: data.table, caret. Python: scikit-learn, imblearn)
Jun 2018 – July 2018

- Validated the loan data on Lending Club, dealt with high missing-rate features and transformed skewed features. 

- Conducted graphical analysis on the imbalanced response, good (92) or bad (1) loan, and utilized 98 mixed-type features and ~97K loan records to construct the machine learning model. 

- Attempted the pipeline with different samplers or weight-penalized machine learning method, and determined an XGBoost with AUPRC 0.9241 ( precision-driven: precision 0.9857) and an SMOTE plus logistic regression with AUPRC 0.9151( recall-driven: recall 0.8622), and visualized the default reason by the feature importance plot. 


## [Story of 3-Point NBA Player (Tableau)](https://public.tableau.com/profile/pengfei.li6575#!/vizhome/nbaStat1950-2017/Story1)
Apr 2018 – May 2018

- Visualized the number of players from U.S. states on the geometrical map, and concluded a "stick" shape of high 3P\% (3-Point Field Goal Rate) players.

- Built a dashboard to track descriptive 3-Point statistics: 3P\%, 3PAr (3P Field Goal Attempt Rate), and 3P (3P Field Goals) of top 3-Point players from 2010 to 2017.

- Created an animation of 3-D Shooter by plotting 3P\% and Dbpm (defense contribution) to justify a sharply increasing demand for 3-D players.



## [Churn Prediction and Recommendation of A MusicBox (Python: pyspark, scikit-learn, graphLab, ALS)](https://github.com/peleonard/MusicBoxCapstone)
Jun 2018 – Jul 2018 

- Cleansed the log dataset (\textasciitilde14G), employed pyspark to generate user behaviors features and the churn label.

- Performed the exploratory data analysis to visualize the relationship between features and the label (churn or not).

- Constructed a stacking model with test AUC 0.9337 (formerly around 0.85), and summarized the churn reason.

- Defined the implicit rating, and bucketed it into 5 levels to mimic practical users' star rating. 

- Built popularity-based recommender, item-item collaborative filtering, and matrix factorization recommender with RMSE 1.0027 (graphLab) and 1.188 (pyspark ALS), previously 1.3~1.5.


## Chatbot by Seq-2-Seq Model (Python: re and TensorFlow)
Apr 2018 – May 2018

- Utilized basic NLP to parse and clean the original movie conversations dataset, 220K Questions and Answers, 50K words, and attained the final input and output. 

- Referring to neural machine translation, constructed two stacked LSTMs: encoder LSTMs and decoder LSTMs with attention mechanisms to mimic the human brain tackling the conversation.

- Trained the model with learning rate decay and the dropout method for 100 epochs and achieved simple chat with the machine.



## Yelp Dataset by SQL (SQLite)
Mar 2018 – Apr 2018

- Determined the data model by ER (entity relationship) diagram, retrieved data from the relational database and interpreted the implications in source data, e.g. relationships between rating stars and operation of hours.

## Analysis of Methylation Patterns in Whole Genome Bisulfite Sequencing Data (R: data.table HiddenMarkov)
Nov 2017 – Feb 2018

- Explored the data, devised an HMM (2M length) to classify CpG islands and non-CpG islands and acquired 94.4\% sensitivity and 70.0\% PPV on CpG level, and 80.4\% and 45.9\% on island level, and accessed the error by CART. 

- Developed a package RcppMovStat, to efficiently calculate moving statistics of the unevenly spaced 2M length sequence within 3 minutes, the window size 500, 5~6x faster than current package, and deployed a shinyApp. 

- Paralleling computation with \textit{mclapply}, sped up the logistic regression and simulation over the chromosome by 5x.


## [A R Package RcppMovStat](https://peleonard.github.io/R_pkg.html)
Oct 2017 – Nov 2017

- Built an R package using Rcpp, using its syntactic sugar, gluing C++ to R}

- Calculated moving statistics, e.g. moving average, 5 ~ 6 times than
similar packages efficiently and designed a routine to obtain moving statistics for unevenly spaced data.

- The two features above make it possible to calculate the moving average on a sequence of a 2-million length within 2 ~ 3 minutes, and deployed a shinyApp.



## Overview of Supervised Learning

- Built a framework of generalized basis expansion quantitative prediction: subset selection, bias-variance trade-off, accessing statistical accuracy.
- Analyzed a dataset following above procedures.
- Obtained an optimal model based on the tabular errors and visualized uncertainty in Matlab.




